services:
  - type: web
    name: colok-colok
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_MODE
        value: demo
      - key: MAX_UPLOAD_MB
        value: 10
      - key: MODEL_PATH
        value: models/best_model_xgboost_final.pkl
      - key: NO_CALL_THRESHOLD
        value: 0.60
