services:
  - type: web
    name: genome-firewall
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_MODE
        value: demo
      - key: MAX_UPLOAD_MB
        value: 10
      - key: GCP_PROJECT_ID
        sync: false
      - key: GCP_REGION
        value: us-central1
      - key: GCP_ENDPOINT_ID
        sync: false
      - key: GCP_SERVICE_ACCOUNT_JSON_BASE64
        sync: false

